name: beyondunreal wiki copy manual
run-name: beyondunreal wiki copy manual
on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pwd
