name: beyondunreal wiki copy manual
run-name: beyondunreal wiki copy manual
on:
  workflow_dispatch:
    inputs:
      path:
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          mkdir beyondunrealwiki
          cd beyondunrealwiki
          curl http://wiki.beyondunreal.com/${{ inputs.path }}>${{ inputs.path }}
          git add .
          git commit -m 'beyondunreal wiki copy manual'
          git push origin HEAD:main
