name: mc-to-lac
run-name: mc-to-lac
on:
  workflow_dispatch:
    inputs:
      savepath:
        required: true
      outpath:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: permissions for mc-to-lac.sh
        run: chmod +x ./mc-to-lac.sh
      - run: ./mc-to-lac.sh
        env:
          SAVEPATH: ${{ inputs.savepath }}
          OUTPATH: ${{ inputs.outpath }}
          ACTOR: ${{ github.actor }}
