name: num
run-name: num
on:
  workflow_dispatch:
    inputs:
      amount:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/workflows/num.sh
        env:
          AMOUNT: ${{ inputs.amount }}
          ACTOR: ${{ github.actor }}
