name: num
run-name: num
on:
  workflow_dispatch:
    inputs:
      amount:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: permissions for num.sh
        run: chmod +x ./num.sh
      - run: ./num.sh
        env:
          AMOUNT: ${{ inputs.amount }}
          ACTOR: ${{ github.actor }}
